[build]
  command = 'npm run build'
  publish = '.next'

[[plugins]]
  package ="netlify-plugin-cypress"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200


[[edge_functions]]
  function = 'geo-header'
  path = '/test'