[build]
  command = 'npm run build'
  publish = '.next'

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = '/contact-us/'
  to = '/404'

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200


[[edge_functions]]
  function = 'geo-header'
  path = '/test'