[build]
  command = 'npm run build'
  publish = '.next'

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = '/contact-us'
  to = '/about-me'

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200



[[redirects]]
  from = '/google'
  to = 'https://www.google.com/'


[[edge_functions]]
  function = 'geo-header'
  path = '/test'