[build]
  command = 'npm run build'
  publish = '.next'

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200
  
  
[[redirects]]
from = '/movie/338953'
to = 'https://www.youtube.com/watch?v=0DrhLDabgmo'
status = 200


[[edge_functions]]
  function = 'geo-header'
  path = '/test'
